 
name: build and push on dockerhub
on: 
  pull_request:
    types: [closed]
    branches:
    - master
env:
  APP_VERSION: "1.0.0"
jobs:
  build-app:
    needs: test
    runs-on: ubuntu-latest
    steps:
          - name: recup repo 
            uses: actions/checkout@v3
          - name: installation de Qemu
            uses: docker/setup-qemu-action@v1
          - name: installation de docker build-app
            uses: docker/setup-buildx-action@v1
          - name: Login au docker hub
            uses: docker/login-action@v1
            with:
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_PASSWORD}}
          - name: build & push docker
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true 
              tags: ${{secrets.DOCKER_USERNAME}}/pytest:${{env.APP_VERSION}}
